apiVersion: v1
kind: Service
metadata:
  name: bedrock-service
  namespace: bedrock-app
  labels:
    app: bedrock-service
spec:
  type: ClusterIP
  selector:
    app: bedrock-service
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
